export const chunks = [
    [
        {
            id: 941,
            downStep: [Object],
            sentence: '暗い夜道はキミガ悪い',
            particle: [Object],
            katakana: 'キミ',
            audioFile: 'audio/examples/気味.reibun00809FE_0504.wav',
            wordId: 9340,
            nasal: '',
            unVoiced: '',
        },
        {
            id: 944,
            downStep: [Object],
            sentence: 'やや楽観ムードのキミガある',
            particle: [Object],
            katakana: 'キミ',
            audioFile: 'audio/examples/気味.reibun00809DB_0538.wav',
            wordId: 9341,
            nasal: '',
            unVoiced: '',
        },
        {
            id: 1412,
            downStep: [Object],
            sentence: '良い卵のキミワ盛り上がっている',
            particle: [Object],
            katakana: 'キミ',
            audioFile: 'audio/examples/黄身.reibun00BA36A_0284.wav',
            wordId: 13492,
            nasal: '',
            unVoiced: '',
        },
        {
            id: 4392,
            downStep: [Object],
            sentence: '無視されたのかキミトも呼ばれず',
            particle: [Object],
            katakana: 'キミ',
            audioFile: 'audio/examples/君.reibun0055A4B_0148.wav',
            wordId: 44261,
            nasal: '',
            unVoiced: '',
        },
    ],
    [
        {
            id: 942,
            downStep: [Object],
            sentence: '暗い夜道はキビガ悪い',
            particle: [Object],
            katakana: 'キビ',
            audioFile: 'audio/examples/気味.reibun0080A09_0100.wav',
            wordId: 9340,
            nasal: '',
            unVoiced: '',
        },
        {
            id: 943,
            downStep: [Object],
            sentence: 'やや楽観ムードのキビガある',
            particle: [Object],
            katakana: 'キビ',
            audioFile: 'audio/examples/気味.reibun00809CF_056C.wav',
            wordId: 9341,
            nasal: '',
            unVoiced: '',
        },
    ],
]
