# This is a basic workflow to help you get started with Actions

name: normalTests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: NPM or Yarn install with caching
              uses: bahmutov/npm-install@v1.1.0
            - name: run tests
              run: yarn run jest  --testPathIgnorePatterns="dataCleaning" --detectOpenHandles
